name: Add Issues to Project
on:
  workflow_dispatch:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main
  # schedule:
  #   - cron: '0 0 * * 1' # At 00:00 on Monday

jobs:
  add-issues:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.VELOCITAS_PROJECT_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install GH CLI
        uses: sersoft-gmbh/setup-gh-cli-action@v1
        with:
          version: latest
      - name: execute add issue python script
        run: python src/main.py

